#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
   require __DIR__.'/../../autoload.php';
} else {
   require __DIR__.'/vendor/autoload.php';
}

use League\Flysystem\Filesystem;
use HeisenbergInstaller\Commands\Update;
use HeisenbergInstaller\Commands\Install;
use HeisenbergInstaller\Commands\Cleanup;
use Symfony\Component\Console\Application;
use League\Flysystem\Adapter\Local as Adapter;

$filesystem = new Filesystem(new Adapter(getcwd().'/'));

$app = new Application("The Heisenberg Installer", "0.5.0");

$app->add(new Install($filesystem));
$app->add(new Cleanup($filesystem));
//$app->add(new Update($filesystem));

$app->run();
