#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Heisenberg Installer', '0.4.3');
$app->add(new Heisenberg\Installer\Console\InstallCommand);
$app->add(new Heisenberg\Installer\Console\CleanupCommand);

$app->run();
